import HomogeneousObstruction.StabilityCertificateManuscript
import HomogeneousObstruction.Obstruction

namespace HomogeneousObstruction

#print axioms mainTheorem_item2
#print axioms mainTheorem_item3

end HomogeneousObstruction
